const mongoose=require('mongoose')
const ProfileSchema=new mongoose.Schema({
    user:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'user'
    },
    company:{
        type:String
    },
    webiste:{
        type:String
    },
    location:{
        type:String
    },
    status:{
        type:String,
        required:true
    },
    skills:{
        type:[String],
        required:true
    },
    bio:{
        type:String
    },
    githubUserName:{
        type:String
    },
    experiences:[{
        title:{
            type:String,
            required:true
        },
        company:{
            type:String,
            required:true
        },
        location:{
            type:String
        },
        from:{
            type:Date,
            required:true
        },
        to:{
            type:Date
        },
        current:{
            type:Boolean,
            default:false
        },
        description:{
            type:String
        }

    }],
    education:[{
        schoolName:{
            type:String,
            required:true
        },
        degree:{
            type:String,
            required:true
        },
        branch:{
            type:String,
            required:true
        },
        from:{
            type:Date,
            required:true
        },
        to:{
            type:Date
        },
        current:{
            type:Boolean,
            default:false
        },
        description:{
            type:String
        }


    }],
    socialMedia:{
        facebook:{
            type:String
        },
        instagram:{
            type:String
        },
        snapchat:{
            type:String
        },
        linkedin:{
            type:String
        },
        twitter:{
            type:String
        }
    },
    date:{
        type:Date,
        default:Date.now
    }
})
module.exports=Profile=mongoose.model('profile',ProfileSchema)